#cloud-config
runcmd:
  - sudo apt-get update
  - sudo apt-get install apt-transport-https ca-certificates curl software-properties-common nmap -y
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository 'deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable'
  - sudo apt-get install docker-ce docker-compose -y
  - sudo echo "vm.max_map_count=262144" >> /etc/sysctl.conf